### ISSUE TITLE
multiple floating ip pools

### ISSUE THREAD

**Issue by sakibsyl** [puppetlabs/puppetlabs-openstack#173]
Is there a way to create multiple floating ip pools using hiera.

openstack::network::external::ippool::start: 192.168.1.100
openstack::network::external::ippool::end: 192.168.1.200

**Comment by cmurphy** [comment]
Looks like not. However, it seems like it would be reasonably easy to add a parameter or change these parameters to accept an array of ['start=x.x.x.x,end=x.x.x.x', ...] instead of just specifying one start and one end.

**Comment by sakibsyl** [comment]
I couldn't figure it out. I'm not sure how to pass these array ['start=x.x.x.x,end=x.x.x.x', ...] and where exactly I can add parameters. 

Here is what I'm trying to achieve.
Private (Tenant network) - 10.50.50.0/24
Public (Internet) - 192.168.1.0/25

And, now I'm trying to add another public network which is 
Public (Internet) 10.60.60.0/24


-Sakib

**Comment by cmurphy** [comment]
In https://github.com/cmurphy/puppetlabs-openstack/commit/308643afd87f08f0a249f1da21582648474aa7be we changed the network resource creation to be more free-form so that you can just use a hash of neutron_subnets in your hiera data. The example hiera data should give you an idea of how to do this now.
