### ISSUE TITLE
Juno - Glance is not correctly configured

### ISSUE THREAD

**Issue by Oyabi** [puppetlabs/puppetlabs-openstack#200]
Hi,
I have seen that glance is not really properly configured with version 5.1 of this module.
Indeed, I have to modify `identity_uri = http://127.0.0.1:35357` by default to `identity_uri = http://my.keystone.server:35357` in `/etc/glance/glance-api.conf` and  `/etc/glance/glance-registry.conf` with Ubuntu 14.04.
If I rerun puppet, no change was occured so I guess it's a bug or an oversight.

Regards.

**Comment by Islam-Nasreddine** [comment]
Salam alikom,
# I have a solution to all glance problems:
the constructor of puppetlabs-openstack module was forgotten to install glance registry service in the storage, this error make your **identity_uri** variable unchangeable.
because glance *api* and *registry* is installed in storage node [you can see here the architecture with list of services] (https://github.com/puppetlabs/puppetlabs-openstack/blob/master/examples/RolesProfiles.pdf).
you need to change somme files in this module to correct this problem, so luts go
## step 01:
add registry installation to this file **/etc/puppet/modules/openstack/manifests/role/storage.pp** :
class openstack::role::storage inherits ::openstack::role {
  class { '::openstack::profile::firewall': }
  class { '::openstack::profile::glance::api': }
  **class { '::openstack::profile::glance::registry': }** #this line is forgoten
  class { '::openstack::profile::cinder::volume': }
  class { '::openstack::setup::cirros': }
}
## step 02: 
install **glance** and **python-glanceclient** packages rather than **glance-api** and **glance-registry**
because these two last packages is not for openstack juno release, [you can se here the correct name of glance packages in install guide] (http://docs.openstack.org/juno/install-guide/install/apt/content/glance-install.html).
so to do this go to **/etc/puppet/modules/glance/manifests/params.pp** and change these two lines:
       $api_package_name      = 'glance-api' 
       $registry_package_name = 'glance-registry' 
to
      $api_package_name      = 'glance' 
      $registry_package_name = 'python-glanceclient' 

finally i think everything is will be **insha Allah** correct,
if you have any other problem, I’m here to help you.
thinks.

**Comment by Oyabi** [comment]
Oh nice, thank you very much.
Can you make a commit please ?

**Comment by cmurphy** [comment]
@Islam-Nasreddine see my comment on #195, your corrections are not relevant to the problem brought up in this issue. 

@Oyabi thanks for bringing this up, the glance module deprecated the auth_* parameters in favor of the identity_uri parameter in https://review.openstack.org/#/c/152321/ but this module has not yet switched over. I've opened https://tickets.puppetlabs.com/browse/OS-258 as a task for this work.
