### ISSUE TITLE
Facing neutron-lbaas is not working

### ISSUE THREAD

**Issue by cooldharma06** [puppetlabs/puppetlabs-openstack#216]
i tried allinone. Everything installed fine. but i am facing the following error in neutron-server.log

2015-07-17 00:15:03.110 29850 ERROR neutron.services.service_base [-] No providers specified for 'LOADBALANCER' service, exiting

for that i did some search and found check neutron-lbaas.conf its not existing under /etc/conf directory.

$ dpkg -l | grep lbaas
ii  neutron-lbaas-agent                      1:2015.1.0-0ubuntu1~cloud0            all          Neutron is a virtual network service for Openstack - LBaaS agent
ii  python-neutron-lbaas                     1:2015.1.0-0ubuntu1~cloud0            all          Loadbalancer-as-a-Service driver for OpenStack Neutron

After searching its related to following bug:
https://bugs.launchpad.net/ubuntu/+source/neutron-lbaas/+bug/1460228

Suggest some solution to solve this.

**Comment by cmurphy** [comment]
This is a packaging error, so I do not believe it is appropriate to try to fix it in puppet.

If we did want to fix it in puppet, it would be in the puppet-neutron module, not this module. You can file a bug for that here: https://launchpad.net/puppet-neutron

**Comment by EmilienM** [comment]
I went on Google because I had this bug. For the record and for people who'll have this bug in the future, you have to enable service_provider parameter in neutron.conf.
See https://bugs.launchpad.net/puppet-neutron/+bug/1535382/comments/1 and https://bugs.launchpad.net/puppet-neutron/+bug/1535382/comments/2 for more details.
